name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   strategy:
      matrix:
        include:
        - name: Windows
          os: windows-latest
        - name: MacOS
          os: macos-latest
        - name: Linux
          os: ubuntu-latest
   name: ${{ matrix.name }}
   runs-on: ${{ matrix.os }}
   steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Run action
      uses: yilinwei/setup-ammonite@yilinwei-patch-1
      with:
        ammonite-version: 2.5.4
        scala-version: 3.1
